"""Table

Revision ID: 45d953e19d70
Revises: 
Create Date: 2021-11-07 10:48:40.503472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d953e19d70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hh_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hh_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hh_id')
    )
    op.create_table('keyskill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vacancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hh_id', sa.Integer(), nullable=False),
    sa.Column('salary_from', sa.Integer(), nullable=True),
    sa.Column('salary_to', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.String(length=128), nullable=True),
    sa.Column('experience_id', sa.String(length=128), nullable=True),
    sa.Column('schedule_id', sa.String(length=128), nullable=True),
    sa.Column('employment_id', sa.String(length=128), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('level', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['employer_id'], ['employer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hh_id')
    )
    op.create_table('vacancy_skill',
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('keyskill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keyskill_id'], ['keyskill.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancy.id'], ),
    sa.PrimaryKeyConstraint('vacancy_id', 'keyskill_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy_skill')
    op.drop_table('vacancy')
    op.drop_table('keyskill')
    op.drop_table('employer')
    op.drop_table('area')
    # ### end Alembic commands ###
